import test from 'node:test';
import assert from 'node:assert/strict';
import {coachRoute,createNominationCoach as createCoach,COACH_SOURCE} from '../dist/nomination-coach.js';
import {readFileSync} from 'node:fs';
const plain=JSON.parse(readFileSync(new URL('../translations/resilience-en.json',import.meta.url)));
const createNominationCoach=()=>{const c=createCoach(),render=c.render;return {...c,render:(a={},g={})=>render(a,g,k=>plain[k]||k)};};
const act=(c,action,value='')=>c.handle({closest:()=>({dataset:{coachAction:action,coachValue:String(value)}})});
const account=Object.freeze({id:'one',type:'demat',holding:'sole',review:'reported',nomination:'missing'});
function advance(c,n){for(let i=0;i<n;i++)act(c,'next');}
test('unsafe routes stop form guidance and actions',()=>{for(const a of [{type:'mf',mfMode:'demat'},{type:'mf',mfMode:'unknown'},{type:'demat',holderDeceased:true}]){const c=createNominationCoach();assert.doesNotMatch(c.render(a),/data-coach-action="next"/);assert.equal(act(c,'next'),false);}assert.equal(coachRoute({type:'bank'}),'bank');});
test('sequential journey requires minor context and produces response intents without tracker mutation',()=>{const c=createNominationCoach();c.render(account);advance(c,3);act(c,'next');assert.match(c.render(account),/Confirm whether your intended nominee/);act(c,'minor','unsure');act(c,'next');assert.match(c.render(account),/Confirm whether your intended nominee/);act(c,'minor','yes');assert.match(c.render(account),/mandatory for a minor nominee/);advance(c,2);assert.equal(act(c,'response','submitted'),'submitted');assert.equal(act(c,'response','blocked'),true);assert.match(c.render(account),/exact reason in writing/);assert.equal(act(c,'record-blocked'),false);act(c,'correction','missing');assert.equal(act(c,'record-blocked'),'blocked');assert.equal(act(c,'response','confirm'),'confirm');assert.equal(act(c,'response','unsure'),true);assert.match(c.render(account),/Keep the current account status unchanged/);assert.equal(account.nomination,'missing');assert.equal(account.review,'reported');});
test('bank guidance never applies securities minor particulars',()=>{const c=createNominationCoach(),a={id:'bank',type:'bank'};c.render(a);advance(c,3);act(c,'minor','yes');const html=c.render(a);assert.match(html,/Ask the bank which date-of-birth/);assert.doesNotMatch(html,/It is mandatory for a minor nominee/);});
test('state follows account context in memory and resets for changed context and clear',()=>{const c=createNominationCoach();c.render(account);advance(c,2);assert.match(c.render(account),/Name the person you want to nominate/);assert.match(c.render({...account,id:'two'}),/Get the right form/);assert.match(c.render(account),/Name the person you want to nominate/);assert.match(c.render({...account,institutionId:'changed'}),/Get the right form/);c.reset();assert.match(c.render(account),/Get the right form/);});
test('deceased toggle blocks an active journey and response intents',()=>{const c=createNominationCoach();c.render(account);act(c,'deceased');assert.match(c.render(account),/Get help after an account holder/);assert.equal(act(c,'next'),false);assert.equal(act(c,'response','confirm'),false);act(c,'deceased');assert.equal(act(c,'next'),true);});
test('official links are HTTPS only and escaped; no personal-input form, course tabs or quizzes',()=>{const c=createNominationCoach();const html=c.render(account,{url:'javascript:alert(1)'});assert.doesNotMatch(html,/javascript:|<input|<textarea|<nav|quiz/i);assert.ok(html.includes(COACH_SOURCE));assert.match(c.render(account,{url:'https://example.org/form'}),/href="https:\/\/example.org\/form"/);assert.equal(act(c,'response','confirm'),false);assert.equal(act(c,'unknown'),false);assert.equal(c.handle(null),false);});
test('response entry supports existing requests while respecting unsupported contexts',()=>{const c=createNominationCoach();assert.equal(c.startResponse(account),true);assert.match(c.render(account),/What does the reply say/);assert.equal(c.startResponse({type:'mf',mfMode:'unknown'}),false);assert.equal(act(c,'response','confirm'),false);});
test('attempted example requires correction and unknown holding blocks handoff',()=>{const c=createNominationCoach(),a={...account,holding:'unknown'};c.render(a);advance(c,2);act(c,'example','holder');act(c,'next');assert.match(c.render(a),/Try the example again/);act(c,'example','nominee');act(c,'next');act(c,'minor','no');advance(c,2);assert.match(c.render(a),/update its account context before submission/);assert.doesNotMatch(c.render(a),/What does the reply say/);});

test('inline example feedback stays expanded after an answer',()=>{const c=createNominationCoach();c.render(account);advance(c,2);act(c,'example','holder');assert.match(c.render(account),/<details open><summary data-speak>Try an example/);act(c,'example','nominee');assert.match(c.render(account),/<details open><summary data-speak>Try an example/);});
test('branch choice carries assisted route to handoff and resets with the session',()=>{const c=createNominationCoach(),guide={specific:true,offline:['Visit the official service desk.'],action:['Use the portal.'],scope:'Applies to this provider.'};c.render(account,guide);act(c,'channel','branch');assert.match(c.render(account,guide),/Which form applies, what consent/);advance(c,3);act(c,'minor','no');act(c,'next');assert.match(c.render(account,guide),/Visit the official service desk/);assert.match(c.render(account,guide),/Step 5 of 6/);c.reset();assert.doesNotMatch(c.render(account,guide),/<h3>At the branch or service desk/);});
test('not submitted returns to handoff; correction reason gates record effect',()=>{const c=createNominationCoach();c.startResponse(account);act(c,'response','not-submitted');assert.match(c.render(account),/Check and send the form/);act(c,'next');act(c,'response','blocked');assert.equal(act(c,'record-blocked'),false);act(c,'correction','wrong');assert.match(c.render(account),/which recorded detail differs/);assert.equal(act(c,'record-blocked'),'blocked');});
test('context and death recovery return parent intents; unsure minor explains recovery immediately',()=>{const c=createNominationCoach();c.render({type:'mf',mfMode:'unknown'});assert.equal(act(c,'edit-context'),'edit-context');c.render(account);act(c,'deceased');assert.equal(act(c,'claim-help'),'claim-help');act(c,'deceased');advance(c,3);act(c,'minor','unsure');assert.match(c.render(account),/then return and choose Yes or No/);act(c,'next');assert.match(c.render(account),/Step 4 of 6/);act(c,'minor','no');act(c,'next');assert.match(c.render(account),/Step 5 of 6/);});

test('a mistaken inheritance answer must be corrected before the guidance continues',()=>{const c=createNominationCoach();c.render(account);advance(c,2);act(c,'example','nominee');act(c,'rights','yes');act(c,'next');assert.match(c.render(account),/Step 3 of 6/);assert.match(c.render(account),/does not decide who legally inherits/);act(c,'rights','no');act(c,'next');assert.match(c.render(account),/Step 4 of 6/);assert.equal(account.review,'reported');});
test('a saved blocked request can enter correction guidance without restarting form preparation',()=>{const c=createNominationCoach();assert.equal(c.startCorrection(account),true);const html=c.render(account);assert.match(html,/Step 6 of 6/);assert.match(html,/What reason did it give/);assert.equal(act(c,'record-blocked'),false);act(c,'correction','unexplained');assert.equal(act(c,'record-blocked'),'blocked');assert.equal(c.startCorrection({type:'mf',mfMode:'unknown'}),false);});
test('offline signing guidance applies to securities and does not import its witness rule into banks',()=>{
 const c=createNominationCoach();const securities={id:'signing-fixture',type:'demat',holding:'sole'};
 c.render(securities);act(c,'channel','branch');assert.match(c.render(securities),/offlineSignatureHelp/);
 const bank={id:'bank-signing-fixture',type:'bank',holding:'sole'};c.render(bank);act(c,'channel','branch');assert.doesNotMatch(c.render(bank),/offlineSignatureHelp/);
});
