import test from 'node:test';
import assert from 'node:assert/strict';
import {coachRoute,createNominationCoach,COACH_SOURCE} from '../dist/nomination-coach.js';
const act=(c,action,value='')=>c.handle({closest:()=>({dataset:{coachAction:action,coachValue:String(value)}})});
const account=Object.freeze({id:'one',type:'demat',holding:'sole',review:'reported',nomination:'missing'});
function advance(c,n){for(let i=0;i<n;i++)act(c,'next');}
test('unsafe routes stop form guidance and actions',()=>{for(const a of [{type:'mf',mfMode:'demat'},{type:'mf',mfMode:'unknown'},{type:'demat',holderDeceased:true}]){const c=createNominationCoach();assert.doesNotMatch(c.render(a),/data-coach-action="next"/);assert.equal(act(c,'next'),false);}assert.equal(coachRoute({type:'bank'}),'bank');});
test('sequential journey requires minor context and produces response intents without tracker mutation',()=>{const c=createNominationCoach();c.render(account);advance(c,3);act(c,'next');assert.match(c.render(account),/Confirm whether your intended nominee/);act(c,'minor','unsure');act(c,'next');assert.match(c.render(account),/Confirm whether your intended nominee/);act(c,'minor','yes');assert.match(c.render(account),/mandatory for a minor nominee/);advance(c,2);assert.equal(act(c,'response','submitted'),'submitted');assert.equal(act(c,'response','blocked'),true);assert.match(c.render(account),/exact rejection or correction reason/);assert.equal(act(c,'record-blocked'),false);act(c,'correction','missing');assert.equal(act(c,'record-blocked'),'blocked');assert.equal(act(c,'response','confirm'),'confirm');assert.equal(act(c,'response','unsure'),true);assert.match(c.render(account),/Keep the current account status unchanged/);assert.equal(account.nomination,'missing');assert.equal(account.review,'reported');});
test('bank guidance never applies securities minor particulars',()=>{const c=createNominationCoach(),a={id:'bank',type:'bank'};c.render(a);advance(c,3);act(c,'minor','yes');const html=c.render(a);assert.match(html,/Ask the bank which date-of-birth/);assert.doesNotMatch(html,/It is mandatory for a minor nominee/);});
test('state follows account context in memory and resets for changed context and clear',()=>{const c=createNominationCoach();c.render(account);advance(c,2);assert.match(c.render(account),/Enter the intended nominee/);assert.match(c.render({...account,id:'two'}),/Start with the correct/);assert.match(c.render(account),/Enter the intended nominee/);assert.match(c.render({...account,institutionId:'changed'}),/Start with the correct/);c.reset();assert.match(c.render(account),/Start with the correct/);});
test('deceased toggle blocks an active journey and response intents',()=>{const c=createNominationCoach();c.render(account);act(c,'deceased');assert.match(c.render(account),/Get help after an account holder/);assert.equal(act(c,'next'),false);assert.equal(act(c,'response','confirm'),false);act(c,'deceased');assert.equal(act(c,'next'),true);});
test('official links are HTTPS only and escaped; no personal-input form, course tabs or quizzes',()=>{const c=createNominationCoach();const html=c.render(account,{url:'javascript:alert(1)'});assert.doesNotMatch(html,/javascript:|<input|<textarea|<nav|quiz/i);assert.ok(html.includes(COACH_SOURCE));assert.match(c.render(account,{url:'https://example.org/form'}),/href="https:\/\/example.org\/form"/);assert.equal(act(c,'response','confirm'),false);assert.equal(act(c,'unknown'),false);assert.equal(c.handle(null),false);});
test('response entry supports existing requests while respecting unsupported contexts',()=>{const c=createNominationCoach();assert.equal(c.startResponse(account),true);assert.match(c.render(account),/What response did the institution/);assert.equal(c.startResponse({type:'mf',mfMode:'unknown'}),false);assert.equal(act(c,'response','confirm'),false);});
test('attempted example requires correction and unknown holding blocks handoff',()=>{const c=createNominationCoach(),a={...account,holding:'unknown'};c.render(a);advance(c,2);act(c,'example','holder');act(c,'next');assert.match(c.render(a),/Try the example again/);act(c,'example','nominee');act(c,'next');act(c,'minor','no');advance(c,2);assert.match(c.render(a),/update its account context before submission/);assert.doesNotMatch(c.render(a),/What response did the institution/);});

test('inline example feedback stays expanded after an answer',()=>{const c=createNominationCoach();c.render(account);advance(c,2);act(c,'example','holder');assert.match(c.render(account),/<details open><summary>Help with name and relationship/);act(c,'example','nominee');assert.match(c.render(account),/<details open><summary>Help with name and relationship/);});
test('branch choice carries assisted route to handoff and resets with the session',()=>{const c=createNominationCoach(),guide={specific:true,offline:['Visit the official service desk.'],action:['Use the portal.'],scope:'Applies to this provider.'};c.render(account,guide);act(c,'channel','branch');assert.match(c.render(account,guide),/Which form applies, what consent/);advance(c,3);act(c,'minor','no');act(c,'next');assert.match(c.render(account,guide),/Visit the official service desk/);assert.match(c.render(account,guide),/Step 5 of 6/);c.reset();assert.doesNotMatch(c.render(account,guide),/<h3>At the branch or service desk/);});
test('not submitted returns to handoff; correction reason gates record effect',()=>{const c=createNominationCoach();c.startResponse(account);act(c,'response','not-submitted');assert.match(c.render(account),/Check consent and submit/);act(c,'next');act(c,'response','blocked');assert.equal(act(c,'record-blocked'),false);act(c,'correction','wrong');assert.match(c.render(account),/which recorded detail differs/);assert.equal(act(c,'record-blocked'),'blocked');});
test('context and death recovery return parent intents; unsure minor explains recovery immediately',()=>{const c=createNominationCoach();c.render({type:'mf',mfMode:'unknown'});assert.equal(act(c,'edit-context'),'edit-context');c.render(account);act(c,'deceased');assert.equal(act(c,'claim-help'),'claim-help');act(c,'deceased');advance(c,3);act(c,'minor','unsure');assert.match(c.render(account),/then return and choose Yes or No/);act(c,'next');assert.match(c.render(account),/Step 4 of 6/);act(c,'minor','no');act(c,'next');assert.match(c.render(account),/Step 5 of 6/);});
