// Publish one effective dictionary per language; authoring tables are never loaded by the app.
import {mkdir,writeFile,readFile,readdir,rm} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {dictionaries} from './dictionaries.mjs';
import {languageInfo,isRTL,audioLanguages} from '../dist/languages.js';
import {loadingText} from '../dist/locale.js';
const languages=languageInfo.filter(([code])=>Object.hasOwn(dictionaries,code));
const root=new URL('../dist/',import.meta.url),catalog={};
await mkdir(new URL('locales/',root),{recursive:true});
for(const [language,dictionary] of Object.entries(dictionaries)){
 const data=JSON.stringify(dictionary),revision=createHash('sha256').update(data).digest('hex').slice(0,12);
 const file=`${language}-${revision}.json`;catalog[language]='/locales/'+file;
 await writeFile(new URL('locales/'+file,root),data);
}
for(const file of await readdir(new URL('locales/',root)))if(!Object.values(catalog).includes('/locales/'+file))await rm(new URL('locales/'+file,root));
await writeFile(new URL('locale-catalog.js',root),'// Generated by scripts/build-locales.mjs.\nexport const localeCatalog='+JSON.stringify(catalog)+';\n');
await writeFile(new URL('locale-retry.js',root),'// Generated native retry labels remain available before a language pack loads.\nexport const nativeRetry='+JSON.stringify(Object.fromEntries(Object.entries(dictionaries).map(([code,d])=>[code,d.audioRetry])))+';\n');
const configPath=new URL('../vercel.json',import.meta.url),config=JSON.parse(await readFile(configPath,'utf8'));
const bootstrap=await readFile(new URL('./startup-inline.js',import.meta.url),'utf8');
if(bootstrap.includes('</script>'))throw Error('Unsafe bootstrap script boundary');
const scriptPolicy="script-src 'self' 'sha256-"+createHash('sha256').update(bootstrap).digest('base64')+"'";
for(const rule of config.headers)for(const header of rule.headers)if(header.key==='Content-Security-Policy')header.value=header.value.replace(/script-src 'self'(?: 'sha256-[^']+')*/g,scriptPolicy);
config.rewrites[0].source='/:locale('+languages.map(([code])=>code).join('|')+')';
await writeFile(configPath,JSON.stringify(config,null,2)+'\n');
// Language entry links can show useful localised text immediately, without waiting for scripts.
let template=await readFile(new URL('index.html',root),'utf8');
template=template.replace(/script-src 'self'(?: 'sha256-[^']+')*/g,scriptPolicy);
template=template.replace('<script type="module" src="/main.js"></script>','<link rel="modulepreload" href="/main.js"><script id="startup-bootstrap"></script>');
template=template.replace(/<script id="startup-bootstrap">[\s\S]*?<\/script>/,()=>'<script id="startup-bootstrap">'+bootstrap+'</script>');
if(!template.includes('id="startup-bootstrap"'))throw Error('Missing recovery bootstrap slot');
const escape=value=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
template=template.replace(/<div class="language-tiles">[\s\S]*?<\/div>/,`<div class="language-tiles">${languages.map(([code,label,name])=>`<a href="/${code}" data-language="${code}" lang="${code}"><strong dir="${isRTL(code)?'rtl':'ltr'}">${label}</strong><span lang="en">${name}</span></a>`).join('')}</div>`);
await writeFile(new URL('index.html',root),template);
await mkdir(new URL('entry/',root),{recursive:true});
// Deferred or removed languages must not leave directly addressable entry pages.
for(const file of await readdir(new URL('entry/',root)))if(file.endsWith('.html')&&!languages.some(([code])=>file===code+'.html'))await rm(new URL('entry/'+file,root));
for(const [language,d] of Object.entries(dictionaries)){
 const t=key=>escape(d[key]),direction=isRTL(language)?'rtl':'ltr';
 let html=template.replace('<html lang="en">',`<html lang="${language}">`).replace('<body class="language-gate">',`<body class="${isRTL(language)?'urdu':''}">`)
  .replace('</head>',`<link rel="preload" href="${catalog[language]}" as="fetch" crossorigin="anonymous"></head>`)
  .replace('<header class="site-header" hidden>','<header class="site-header">')
  .replace(/<main id="main"[\s\S]*?<\/main>/,`<main id="main" class="app-shell" tabindex="-1" aria-busy="true"><div class="page-heading"><h1 dir="${direction}">${t('homeTitle')}</h1><p dir="${direction}">${t('homeIntro')}</p><p class="micro language-status" role="status" lang="${language}" dir="${direction}">${loadingText[language]||'…'}</p><a class="startup-retry" href="/${language}">${t('audioRetry')}</a></div><noscript><p>JavaScript is needed for this private, local account guide.</p></noscript></main>`)
  .replace('aria-label="Home"',`aria-label="${t('home')}"`)
  .replace('id="language-button" class="language-button" aria-haspopup="dialog"></button>',`id="language-button" class="language-button" aria-label="${t('language')}" aria-haspopup="dialog">${languages.find(([code])=>code===language)[1]}</button>`)
  .replace('id="access-toggle" class="icon-button"',`id="access-toggle" class="icon-button" aria-label="${t('readingSettings')}"`)
  .replace(/<button type="button"/g,'<button type="button" disabled data-startup-disabled');
 // A failed language load still leaves native links for a simple retry.
 html=html.replace('</main>',`<div class="startup-languages language-tiles" hidden>${languages.map(([code,label])=>`<a href="/${code}" data-language="${code}" lang="${code}">${label}</a>`).join('')}</div></main>`);
 await writeFile(new URL(`entry/${language}.html`,root),html);
}
const worker=new URL('sw.js',root);
let sw=(await readFile(worker,'utf8')).replace(/const LOCALES=.*?; \/\/ Generated by build-locales.mjs\./,'const LOCALES='+JSON.stringify(catalog)+'; // Generated by build-locales.mjs.');
sw=sw.replace(/const AUDIO_LANGUAGES=.*?; \/\/ Generated by build-locales.mjs\./,'const AUDIO_LANGUAGES='+JSON.stringify(audioLanguages)+'; // Generated by build-locales.mjs.');
// Every public-shell edit changes the offline version; stale workers never mix releases.
const hash=createHash('sha256').update(sw.replace(/const SHELL='[^']+'/,"const SHELL='VERSION'"));
const files=[...sw.match(/const FILES=\[([^\]]+)\]/)[1].matchAll(/'([^']+)'/g)].map(match=>match[1]);
for(const file of [...files,'/fonts/noto-sans-meetei-mayek.woff2','/fonts/noto-sans-ol-chiki.woff2'])hash.update(file).update(await readFile(new URL(file.slice(1),root)));
sw=sw.replace(/const SHELL='[^']+'/,`const SHELL='virasat-shell-${hash.digest('hex').slice(0,12)}'`);
await writeFile(worker,sw);
console.log(catalog);
