// Publish one effective dictionary per language; authoring tables are never loaded by the app.
import {mkdir,writeFile,readFile,readdir,rm} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {dictionaries} from '../dist/i18n.js';
import {sessionText} from '../dist/session-policy.js';
import {loadingText,languages} from '../dist/locale.js';
const root=new URL('../dist/',import.meta.url),catalog={};
await mkdir(new URL('locales/',root),{recursive:true});
for(const [language,dictionary] of Object.entries(dictionaries)){
 const data=JSON.stringify(dictionary),revision=createHash('sha256').update(data).digest('hex').slice(0,12);
 const file=`${language}-${revision}.json`;catalog[language]='/locales/'+file;
 await writeFile(new URL('locales/'+file,root),data);
}
for(const file of await readdir(new URL('locales/',root)))if(!Object.values(catalog).includes('/locales/'+file))await rm(new URL('locales/'+file,root));
await writeFile(new URL('locale-catalog.js',root),'// Generated by scripts/build-locales.mjs.\nexport const localeCatalog='+JSON.stringify(catalog)+';\n');
// Language entry links can show useful localised text immediately, without waiting for scripts.
const template=await readFile(new URL('index.html',root),'utf8'),escape=value=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
await mkdir(new URL('entry/',root),{recursive:true});
for(const [language,d] of Object.entries(dictionaries)){
 const t=key=>escape(sessionText(language,key)??d[key]),direction=language==='ur'?'rtl':'ltr';
 let html=template.replace('<html lang="en">',`<html lang="${language}">`).replace('<body class="language-gate">',`<body class="${language==='ur'?'urdu':''}">`)
  .replace('</head>',`<link rel="preload" href="${catalog[language]}" as="fetch" crossorigin="anonymous"></head>`)
  .replace('<header class="site-header" hidden>','<header class="site-header">')
  .replace(/<main id="main"[\s\S]*?<\/main>/,`<main id="main" class="app-shell" tabindex="-1" aria-busy="true"><div class="page-heading"><h1 dir="${direction}">${t('homeTitle')}</h1><p dir="${direction}">${t('homeIntro')}</p><p class="micro language-status" role="status" lang="${language}" dir="${direction}">${loadingText[language]}</p></div><noscript><p>JavaScript is needed for this private, local account guide.</p></noscript></main>`)
  .replace('aria-label="Home"',`aria-label="${t('home')}"`)
  .replace('id="language-button" class="language-button" aria-haspopup="dialog"></button>',`id="language-button" class="language-button" aria-label="${t('language')}" aria-haspopup="dialog">${languages.find(([code])=>code===language)[1]}</button>`)
  .replace('id="access-toggle" class="icon-button"',`id="access-toggle" class="icon-button" aria-label="${t('readingSettings')}"`)
  .replace(/<button type="button"/g,'<button type="button" disabled data-startup-disabled');
 // A failed language load still leaves native links for a simple retry.
 html=html.replace('</main>',`<div class="startup-languages language-tiles" hidden>${languages.map(([code,label])=>`<a href="/${code}" data-language="${code}" lang="${code}">${label}</a>`).join('')}</div></main>`);
 await writeFile(new URL(`entry/${language}.html`,root),html);
}
const worker=new URL('sw.js',root);
let sw=(await readFile(worker,'utf8')).replace(/const LOCALES=.*?; \/\/ Generated by build-locales.mjs\./,'const LOCALES='+JSON.stringify(catalog)+'; // Generated by build-locales.mjs.');
// Every public-shell edit changes the offline version; stale workers never mix releases.
const hash=createHash('sha256').update(sw.replace(/const SHELL='[^']+'/,"const SHELL='VERSION'"));
const files=[...sw.match(/const FILES=\[([^\]]+)\]/)[1].matchAll(/'([^']+)'/g)].map(match=>match[1]);
for(const file of files)hash.update(file).update(await readFile(new URL(file.slice(1),root)));
sw=sw.replace(/const SHELL='[^']+'/,`const SHELL='virasat-shell-${hash.digest('hex').slice(0,12)}'`);
await writeFile(worker,sw);
console.log(catalog);
